version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "demo1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-noxtanttus4"
s3_prefix = "demo1"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
